<?php

namespace AppBundle\Repository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findOneById($value) {
        return $this->createQueryBuilder('a')
                ->andWhere('a.id = :val')
                ->setParameter('val', $value)
                ->getQuery()
                ->getOneOrNullResult()
                ;
    }
}
