<?php

namespace AppBundle\Repository;

/**
 * VaccinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VaccinationRepository extends \Doctrine\ORM\EntityRepository
{
}
