<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTgbp6dh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTgbp6dh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTgbp6dh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTgbp6dh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTgbp6dh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tgbp6dh',
    'container.build_id' => 'cbf1f367',
    'container.build_time' => 1539681800,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerTgbp6dh');
