<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKnzarmq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKnzarmq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKnzarmq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKnzarmq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKnzarmq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Knzarmq',
    'container.build_id' => '9989abcb',
    'container.build_time' => 1539166303,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKnzarmq');
