<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPsq57xe\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPsq57xe/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPsq57xe.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPsq57xe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPsq57xe\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Psq57xe',
    'container.build_id' => 'd6bfcaff',
    'container.build_time' => 1539327467,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPsq57xe');
